### ISSUE TITLE
Auto-Play all files

### ISSUE THREAD

**Issue by Hades32** [feststelltaste/wardley-maps-audiobook#17]
Clicking on the links, listening to the audio, returning to the page, remembering where I was and then repeating the procedure with the next file is cumbersome.

It would be great if we could have a little playlist for an `<audio>` tag which can play all files in order

**Comment by feststelltaste** [comment]
Nice idea, but I think it clutters the homepage. I put now RSS feeds on the website as an alternative. My additional suggestion is to use an audiobook app an import the MP3 files that come in a ZIP file. E.g. the [Voice app on Android](https://play.google.com/store/apps/details?id=de.ph1b.audiobook) is great for this! So this is a won't fix.
