### ISSUE TITLE
Audio with female voice is corrupted

### ISSUE THREAD

**Issue by KO3AK-I3-XOPCY** [feststelltaste/wardley-maps-audiobook#19]
The file https://github.com/feststelltaste/wardley-maps-audiobook/releases/download/v0.1-female/Simon_Wardley_-_Wardley_Maps_-_Topographical_intelligence_in_business_v0.1-female.mp3  does not play beyond like a minute. Scrolling through does not seem to work either.
Male voice version seems fine.

**Comment by feststelltaste** [comment]
Thanks for the hint! There is definitely a problem with the way how I merge MP3 files. Did a quick investigation but couldn't fix it. Will try out different ways ASAP!

**Comment by feststelltaste** [comment]
Fixed it!

**Comment by KO3AK-I3-XOPCY** [comment]
Confirmed fixed, thanks!
