### ISSUE TITLE
EN language issue: "synthetic generated" -> synthetically generated 

### ISSUE THREAD

**Issue by gernotstarke** [feststelltaste/wardley-maps-audiobook#3]
trivial, minior, nitpicking:
from my point of view, it should read "synthetically generated".

**Comment by gernotstarke** [comment]
19min from finding-the-bug until production :-)

the bug-fixer-on-duty did a good job!

**Comment by feststelltaste** [comment]
Thanks for the hint, Gernot! Such kind of improvement suggestions are always welcome, too!
