### ISSUE TITLE
Add an RSS to be included in podcast application

### ISSUE THREAD

**Issue by remyleone** [feststelltaste/wardley-maps-audiobook#8]
It would be useful to have an RSS link that I could add in my podcast application and download this audiobook in the same place I listen to podcasts

**Comment by feststelltaste** [comment]
Great idea! This would be really useful. I'll try to implement it soon.

**Comment by feststelltaste** [comment]
Longer needed that originally tought. Now there are links to RSS files.

**Comment by remyleone** [comment]
I think there is some errors ion the rss feed: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ffeststelltaste.github.io%2Fwardley-maps-audiobook%2Frss_female.xml 

Besides, I've tried to add in pocket cast and it does not work.
