### ISSUE TITLE
MP3 audio cuts off the last 1-2 words of each section

### ISSUE THREAD

**Issue by robertwatkins** [feststelltaste/wardley-maps-audiobook#9]
The last few seconds of the audio sections cut off 1-2 (or even 3) words from the text.

**Comment by feststelltaste** [comment]
Thanks for this hint. I've checked some audio files but couldn't find one were the end was cut off. Do you have an example?

What comes to my mind is that the generated voice could do some weird emphasis at the end of a sentence that makes it sound like cut off.

**Comment by feststelltaste** [comment]
Update: I've experienced the same in rare situations (Windows 10, Groove Music). I can't explain why this would happen. I try to add a 1 second pause at the end of each section in the next release.

**Comment by feststelltaste** [comment]
Will add the pause for the next release. Thanks for the hint!

**Comment by robertwatkins** [comment]
It appears that this is an issue with the built-in mp3 player for my laptop (Microsoft's Groove Music on Windows 10) 

I have confirmed that manually playing just the last few seconds of the tracks I was having issues with could not reproduce the issue. This tells me that it's an issue with the mp3 player knowing how long to keep playing data from a track and not the track itself. 

Thank you for the prompt reply.
